import { waitForGenAi, fillRequiredField } from '@components/commons/helpers';
import { test } from '@fixtures/pages/page-objects.fixture';
import { CopySectionComponent } from '@pageObjects/components/copy-section.component';
import { DownloadImageComponent } from '@pageObjects/components/downloadimage.component';
import { GenerateContentImagePage } from '@pageObjects/pages/gen-ai/generate-content-image.page';
import { expect, Page } from '@playwright/test';
import { APPS_DETAILS } from '@/app/(default)/apps-mapping';
import { MessageFeedbackActionsComponent } from '@pageObjects/components/message-feedback-actions.component';
import { GenerateContentImageEditPage } from '@pageObjects/pages/gen-ai/generate-content-image-edit.page';

const GENERATION_URL_REGEX = new RegExp(
  `.*${APPS_DETAILS.CONTENT_IMAGE.url}/([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})$`
);

test.describe('Generate Content Image Page Tests', () => {
  test.beforeEach(async ({ generateContentImagePage }) => {
    await generateContentImagePage.goto();
  });

  test('[GEN-T353, GEN-T354, GEN-T355] Should generate shareable link for image generation', async ({
    page,
    generateContentImagePage,
  }) => {
    // Given I have generated an image
    await generateContentImagePage.formSection.ideaField.fill('Classic Mayo');
    await generateContentImagePage.formSection.pressGenerateButton();

    // When the generation finished
    // Then the URL should update with the generation ID
    await waitForGenAi(generateContentImagePage);
    await expect(page).toHaveURL(GENERATION_URL_REGEX);
    const generationUrl = page.url();

    // When I click on Copy shareable link
    const copyLinkButton = generateContentImagePage.copyPageLinkComponent.button;
    await expect(copyLinkButton).toBeVisible();
    await copyLinkButton.click();
    // Then the link for that particular generation will be copied and I can share the generation
    const clipboardText = await page.evaluate(() => navigator.clipboard.readText());
    expect(clipboardText).toEqual(generationUrl.trim());
    // And I should see a warning that the link has been copied.
    const copiedButton = generateContentImagePage.copyPageLinkComponent.confirmation;
    await expect(copiedButton).toBeVisible();

    // Given that a user accesses a shareable link generated by another user
    const newPage = await generateContentImagePage.page.context().newPage();
    await newPage.goto(generationUrl);
    const newGenerateContentImagePage = new GenerateContentImagePage(newPage);
    await page.close();
    // When the link view is loaded
    // Then he should only see the 4 images generated in that generation
    expect(await newGenerateContentImagePage.resultsSection.image.count()).toBe(4);
  });

  test('[GEN-T356, GEN-T357, GEN-T359, GEN-T360, GEN-T407, GEN-T408, GEN-T409] Should be able to copy, download, and rate an image and leave optional comment feedback in the feedback modal', async ({
    page,
    generateContentImagePage,
  }) => {
    // Given I have generated an image
    const imageIdea = 'Classic Mayo';
    await fillRequiredField(generateContentImagePage.formSection.ideaField, imageIdea);
    await generateContentImagePage.formSection.pressGenerateButton();
    await waitForGenAi(generateContentImagePage);

    const images = await generateContentImagePage.resultsSection.imageContainer.all();
    for (const image of images) {
      // When I click on the copy button on an image
      // Then the copy icon changes to indicate that the image has been copied
      const copySectionComponent = new CopySectionComponent(image);
      await expect(copySectionComponent.button).toBeVisible();
      await copySectionComponent.button.click();
      await expect(copySectionComponent.confirmationIcon).toBeVisible();

      const downloadImageComponent = new DownloadImageComponent(page, image);
      await expect(downloadImageComponent.button).toBeVisible();

      const imageFeedbackActions = new MessageFeedbackActionsComponent(page, image);
      await imageFeedbackActions.checkFeedbackActionsVisibility();
    }

    // When I click on the download button of a particular image
    const firstImage = generateContentImagePage.resultsSection.imageContainer.first();
    const downloadImageComponent = new DownloadImageComponent(page, firstImage);
    const downloadPromise = downloadImageComponent.clickDownload();
    // Then a toast message is displayed indicating that the image is being downloaded
    await expect(downloadImageComponent.toastMessage).toBeVisible();
    // And the download icon changes to a download transition icon
    await expect(downloadImageComponent.loaderIndicator).toBeVisible();
    const { filename: downloadedFileName } = await downloadPromise;
    // And the the selected image is automatically downloaded to my files
    expect(downloadedFileName).toMatch(`${imageIdea}.png`);

    const imageFeedbackActions = new MessageFeedbackActionsComponent(page, firstImage);
    // Should be able to rate, open the feedback modal, and either submit feedback or close the modal without submitting
    await imageFeedbackActions.checkFeedbackActionsFunctionality();
  });

  test('[GEN-T404, GEN-T426] Should be able to regenerate all images', async ({ generateContentImagePage }) => {
    // Given I have generated an image
    const imageIdea = 'Classic Mayo';
    await fillRequiredField(generateContentImagePage.formSection.ideaField, imageIdea);
    await generateContentImagePage.formSection.pressGenerateButton();
    await waitForGenAi(generateContentImagePage);
    await generateContentImagePage.page.waitForURL(GENERATION_URL_REGEX);
    const firstGeneratedUrl = generateContentImagePage.page.url();
    // When I click the Regenerate all images button for images
    await expect(generateContentImagePage.resultsSection.regenerateButton).toBeVisible();
    await generateContentImagePage.resultsSection.regenerateButton.click();
    await generateContentImagePage.resultsSection.loadingImagesAnimation.waitFor({ state: 'hidden' });
    // Then all 4 images will regenerate in place of the original 4 images
    expect(await generateContentImagePage.resultsSection.image.count()).toBe(4);
    const secondGeneratedUrl = generateContentImagePage.page.url();
    expect(firstGeneratedUrl).not.toEqual(secondGeneratedUrl);
  });

  test('[GEN-T439, GEN-T517, GEN-T438, GEN-T450, GEN-T470, GEN-T471] Should be able to open the edit page and edit the image, with a loading state appearing while the image is being generated and each regeneration should have a unique URL', async ({
    page,
    generateContentImagePage,
  }) => {
    const EDIT_PAGE_URL_REGEX = new RegExp(`.*${APPS_DETAILS.CONTENT_IMAGE.url}/([0-9a-f-]+)/([0-9a-f-]+)/edit$`);

    function getEditIds(editPage: Page) {
      const urlMatch = editPage.url().match(EDIT_PAGE_URL_REGEX);
      return { generationId: urlMatch?.[1], fileId: urlMatch?.[2] };
    }

    // Given I have generated an image
    const imageIdea = 'Classic Mayo';
    await fillRequiredField(generateContentImagePage.formSection.ideaField, imageIdea);
    await generateContentImagePage.formSection.pressGenerateButton();
    await waitForGenAi(generateContentImagePage);
    await generateContentImagePage.page.waitForURL(GENERATION_URL_REGEX);

    // When I click the Edit button on an image
    await generateContentImagePage.resultsSection.editButton.first().click();
    const [newPage] = await Promise.all([
      page.context().waitForEvent('page'),
      generateContentImagePage.resultsSection.editButton.first().click(),
    ]);

    // I should be taken to the Edit page for that image
    const imageEditingPage = new GenerateContentImageEditPage(newPage);
    await expect(imageEditingPage.root).toBeVisible();
    await expect(imageEditingPage.activeImage).toBeVisible();
    // [GEN-T470] And I see the unique url with format /content/image/:generationId/:fileId/edit
    await expect(newPage).toHaveURL(EDIT_PAGE_URL_REGEX);
    const { generationId: initialGenerationId, fileId: initialFileId } = getEditIds(imageEditingPage.page);

    // Select "Change background to white"
    await imageEditingPage.selectQuickPromptOption('Change background to white');

    // Click "Regenerate" button
    await imageEditingPage.regenerateButton.click();
    // Skeleton should replace active image and regenerate button should be disabled and display a spinner icon during generation
    await expect(imageEditingPage.activeImage).not.toBeVisible();
    await expect(imageEditingPage.loadingSkeleton).toBeVisible();
    await expect(imageEditingPage.regenerateButton).toBeDisabled();
    await expect(imageEditingPage.regenerateButtonLoadingSpinner).toBeVisible();

    // Image should appear when loading finishes
    await expect(imageEditingPage.activeImage).toBeVisible({ timeout: 30000 });
    await expect(imageEditingPage.regenerateButton).not.toBeDisabled();

    // [GEN-T471] And I see the unique url for the regenerated image with format /content/image/:generationId/:fileId/edit
    const { generationId: editGenerationId, fileId: editFileId } = getEditIds(imageEditingPage.page);
    expect(editGenerationId).not.toBe(initialGenerationId);
    expect(editFileId).not.toBe(initialFileId);
  });

  test('[GEN-T350, GEN-T351, GEN-T352] Should be able to select an image generation size', async ({
    generateContentImagePage,
  }) => {
    // GEN-T352 Given I am in the image generation screen
    // When I have not made any selection in the Image Size field
    // Then the “Square” option should be selected by default.
    await expect(generateContentImagePage.formSection.sizeRadioButton.first()).toHaveText('1:1');
    await expect(generateContentImagePage.formSection.sizeRadioButton.first()).toBeChecked();

    // GEN-T350 Given that I have a specific image size that I want to generate
    // When I look at the Image Size field
    await expect(generateContentImagePage.formSection.sizeRadioGroup).toBeVisible();
    const radioOptions = await generateContentImagePage.formSection.sizeRadioButton.count();
    // Then I can select the size and shape options
    const randomIndex = Math.floor(Math.random() * radioOptions);
    const radioOptionName = await generateContentImagePage.formSection.sizeRadioButton.nth(randomIndex).textContent();
    await generateContentImagePage.formSection.sizeRadioButton.nth(randomIndex).click();
    // And I can only select one thumbnail option at a time.
    for (let i = 0; i < radioOptions; i++) {
      const radio = generateContentImagePage.formSection.sizeRadioButton.nth(i);
      const isChecked = await radio.isChecked();
      if (i === randomIndex) {
        expect(isChecked).toBe(true);
      } else {
        expect(isChecked).toBe(false);
      }
    }
    // GEN-351 Then all my images will be generated with the selected size.
    const imageIdea = 'Classic Mayo';
    await fillRequiredField(generateContentImagePage.formSection.ideaField, imageIdea);
    await generateContentImagePage.formSection.pressGenerateButton();
    await waitForGenAi(generateContentImagePage);
    await expect(generateContentImagePage.resultsSection.imageSizeTitle).toBeVisible();
    await expect(generateContentImagePage.resultsSection.imageSize).toHaveText(radioOptionName!);
  });

  test('[GEN-T394] Should the User can view original inputs after generation', async ({ generateContentImagePage }) => {
    // Given I have generated an image with imageIdea, exclude and imageSize
    const imageIdea = 'Classic Mayo Bottle';
    const exclude = 'clear background';
    const imageSize = '1:1';

    await fillRequiredField(generateContentImagePage.formSection.ideaField, imageIdea);
    await fillRequiredField(generateContentImagePage.formSection.excludeField, exclude);
    await generateContentImagePage.formSection.sizeRadioButton.first().click();
    await generateContentImagePage.formSection.pressGenerateButton();
    await waitForGenAi(generateContentImagePage);
    await generateContentImagePage.page.waitForURL(GENERATION_URL_REGEX);

    // When I view the output screen
    // Then I see the original inputs in the results section
    await expect(generateContentImagePage.resultsSection.ideaTitle).toBeVisible();
    await expect(generateContentImagePage.resultsSection.ideaValue).toHaveText(imageIdea);

    await expect(generateContentImagePage.resultsSection.imageSizeTitle).toBeVisible();
    await expect(generateContentImagePage.resultsSection.imageSize).toHaveText(imageSize);

    await expect(generateContentImagePage.resultsSection.excludeTitle).toBeVisible();
    await expect(generateContentImagePage.resultsSection.excludeValue).toHaveText(exclude);

    // And the fields are displayed in a non-editable format
    await expect(generateContentImagePage.resultsSection.root.locator('.bg-neutral-100')).toBeVisible();
  });
});
